#+BEGIN_EXPORT html
---
layout: post
title: Unit Tests In React
---
#+END_EXPORT
#+REVEAL_ROOT: http://cdn.jsdelivr.net/reveal.js/3.0.0/
#+REVEAL_VERSION: 3.0.0
#+REVEAL_THEME: simple
#+OPTIONS: toc:nil
#+TITLE: Unit Tests In React

* Context
** Unit Tests Benefits
- Ensure code correctness at the lowest level
- Prevents bug regressions
- Makes code coverage look cool 😎
#+BEGIN_NOTES
Unit testing is the first tool programmers have to ensure the correctness of
their programs.
#+END_NOTES
** Unit Tests Definition
What makes a unit test a unit test is its scope:

Unit tests should only test one unit a time.
#+BEGIN_NOTES
A unit is a diffuse term but it usually refers to a function or a class. A good
unit test proves the outcome of the unit under test is correct for all it's
logic branches, and for the relevant inputs. Fortunately, reaping the benefits
of unit testing is not hard because the latest developments in technology make
writing unit tests easy.
#+END_NOTES
* Unit Tests Scope In React
- Keep in mind the React component ultimate purpose: to generate HTML code
- A component is a unit
#+BEGIN_NOTES
As in every kind application, React apps benefit from having unit tests, but
they come with their own set of complications. What's generally accepted though,
is that a React component, especially if it's simple as in markup-only
components, but even if it's complex, with state management, children, and
network calls, is an unit. With the exception of higher-order-components,
something we should always keep in mind while testing is a component's
fundamental /purpose/: to generate HTML code. This means that all that state
handling, network calling, and children bearing, will ultimately result in a
tree of HTML tags ready to be rendered by the browser.
#+END_NOTES
* Testing State vs Testing Outcomes
When developing unit tests there are two common approaches:
Testing state and testing outcomes.
** Testing A Unit's State
Testing state is the practice of querying the state of the unit at a given
moment of time. In React, this can be seen in tests that assert the props and/or
the state of the component is what we expect it to be at interesting points in
time, for example, when a component is rendered for the first time, or when a
button has been clicked.
#+BEGIN_SRC js :results output :tangle test.js
  const assert = require('assert/strict');

  function createCounter() {
      let state = { count: 0 };
      return {
          state,
          onClick() {
              state.count += 1;
          },
          render() {
              return `<p>Clicked ${state.count}</p>`;
          },
      };
  }

  const counter = createCounter();

  assert.equal(counter.state.count, 0);
  
  counter.onClick();

  assert.equal(counter.state.count, 1);
#+END_SRC

#+RESULTS:

#+BEGIN_NOTES
My guess is we do this because when we debug we usually make sure the state is
correct step by step during the execution of our program.

What happens if we change the type of ~state.count~?
What happens if we change ~state.count~ for ~state.clicks~?
What happens if we pass the count as parameter (prop) instead of storing it as
state?
What happens if we change the word "Clicked" for "Clidkec" in the render method?
#+END_NOTES
** Testing A Unit's Purpose
Testing outcomes refers to the practice of testing a unit delivers the outcomes
it's designed to deliver. In React, this means we should test a component
delivers the desired HTML code given a known context.
#+BEGIN_SRC js
  const assert = require('assert/strict');

  function createCounter() {
      let state = { count: 0 };
      return {
          state,
          onClick() {
              state.count += 1;
          },
          render() {
              return `<p>Clicked ${state.count}</p>`;
          },
      };
  }

  function getInnerText(html) {
      return html.replace(/\<p\>|\<\/p\>/gi, '');
  }

  const counter = createCounter();

  assert.equal(getInnerText(counter.render()), `Clicked 0`);

  counter.onClick();

  assert.equal(getInnerText(counter.render()), `Clicked 1`);
#+END_SRC

#+RESULTS:
: undefined
** Test Value
The value of a test has to be proposed case by case, it depends on the unit's
purpose.

Let's examine the ~counter~ component.
#+BEGIN_SRC js
  function createCounter() {
      let state = { count: 0 };
      return {
          state,
          onClick() {
              state.count += 1;
          },
          render() {
              return `<p>Clicked ${state.count}</p>`;
          },
      };
  }
#+END_SRC
From the source code, we can tell that the counter component's output is some
HTML code that includes the number of times its ~onClick~ callback has been
called, but in the end, the component's expected /outcome/ is this:

to show a user how many times the counter has been clicked.

Note that neither the fact that the counter comes from state or props, nor if
the text is displayed inside a paragraph or a list item matters to the end user.
** Test Robustness
For every testing approach (testing a unit's state and testing a unit's
purpose), ask the following questions:

- What happens if we change the type of ~state.count~?
- What happens if we change ~state.count~ for ~state.clicks~?
- What happens if we pass the count as parameter (prop) instead of storing it as state?
- What happens if we change the word "Clicked" for "Clidkec" in the render method?
 
In general, test robustness increases when we test outcomes instead of state.
* When To Test The Redux ~connect~ HOC
Redux is a wonderful state management solution that happens to work pretty well
when combined with React using the ~react-redux~ package. The package provides
the ~connect~ HOC which does what its name implies. When we test a component
like this:
#+BEGIN_SRC javascript
  import React from 'react';
  import { connect } from 'react-redux';

  const Prompt = ({ name }) => (<p>{`Hello ${name}!`}</p>);

  const mapStateToProps = (state) => ({ name: state.name });

  export default connect(mapStateToProps)(Prompt);
#+END_SRC
we end up testing 2 things instead of one, making our tests more complex and
brittle than they needed to be.
** Abstract Test Value
*** Does it render?
One of the most common unit tests there are, are the ones that check the
component actually renders with a given set of valid props. If we test the
default export from the component above, we will end up testing that our Redux
setup works (either the real deal or a mocked store), that the connect HOC
doesn't have any logic errors, and that the actual component (~Prompt~) works.
To simplify this test, we should export the ~Prompt~ component separately and
test it in isolation with different props combinations.
*** Does it generate the desired ~props~?
When we have connected components there's something else beside rendering
success that could be considered fundamental: testing the main component is
getting the props it needs. Most of the time, the logic in the ~mapStateToProps~
function is pretty simple, as it should, thus, writing tests for it should be
similarily simple. We have to remember exporting it by itself and testing it
with different inputs to ensure it generates the necessary props.
* How To Test React Components
By adhering to the principle of testing purpose instead of state, we will see
more clearly the tests a component needs, when using the right tools for the job.
** Abstract Test Value
*** Does it render?
Even when successful rendering is implied in other tests, because a component
wouldn't fulfill its purpose if it didn't render in the first place, I like
adding this basic unit test; it is mandatory if you're doing TDD. Now that we
separated the notion of Redux adapter and React component, we know that we
should export the component separately and test it in isolation.
*** Does it generate the desired HTML?
Since we control the props we pass to the component while testing, we can assume
they will be right, so no need to double check them. The purpose of a React
component is to generate HTML, we should be looking at the DOM or virtual DOM
for the expected HTML code.

This means that if we have a component like this:
#+BEGIN_SRC javascript
  import React from 'react';
  import { connect } from 'react-redux';

  export const Prompt = ({ name }) => (<p>{`Hello ${name}!`}</p>);

  const mapStateToProps = (state) => ({ name: state.name });

  export default connect(mapStateToProps)(Prompt);
#+END_SRC
Our most simple test would look like this:
#+BEGIN_SRC javascript
  import React from 'react';
  import { render } from '@testing-library/react';
  import { Prompt } from './Prompt';

  describe("<Prompt />", () => {
    describe("when provided complete and valid props", () => {
      it("renders correctly", () => {
        const name = "Mario";
        const wrapper = render(<Prompt name={name} />);
        expect(wrapper.findByText(name)).toBeInTheDocument();
      });
    });
  });
#+END_SRC
** Testing The Outcomes
Now assume a little more complex component:
#+BEGIN_SRC javascript
  import React, { useState } from 'react';
  import { connect } from 'react-redux';

  export const Prompt = ({ name }) => {
    const [loggedIn, setLoggedIn] = useState(false);
    return (<>
      <p>{loggedIn ? `Hello ${name}!` : "Hello stranger"}</p>
      <button onClick={() => setLoggedIn(!loggedIn)}>click</button>;
    </>);
  };

  const mapStateToProps = (state) => ({ name: state.name });

  export default connect(mapStateToProps)(Prompt);
#+END_SRC

The following test would excercise both logic branches:
#+BEGIN_SRC javascript
  import React from 'react';
  import userEvent from '@testing-library/user-event';
  import { render } from '@testing-library/react';
  import { Prompt } from './Prompt';

  describe("<Prompt />", () => {
    describe("when provided complete and valid props", () => {
      it("renders correctly", () => {
        const name = "Mario";
        const wrapper = render(<Prompt name={name} />);
        expect(wrapper.findByText(name)).toBeInTheDocument();
      });

      it("has a generic greeting", () => {
        const name = "Mario";
        const wrapper = render(<Prompt name={name} />);
        expect(wrapper.findByText(/stranger/)).toBeInTheDocument();
      });

      describe("when the button is clicked once", () => {
        const name = "Mario";
        const wrapper = render(<Prompt name={name} />);
        userEvent.click(wrapper.findByText(/click/));
        expect(wrapper.findByText(name)).toBeInTheDocument();
      });
    });
  });
#+END_SRC
* Final Words
:PROPERTIES:
:UNNUMBERED: notoc
:END:
* QA
